name: On Push Run

on: 
  schedule:
    - cron:  '1 * * * *'

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:   
    - name: Hello World
      run: python mosuke.py
      shell: sh
